[tools]
go = "latest"
watchexec = "latest"

[tasks.dev]
description = "Run Kubernetto and restart when source files change"
run = "mise watch --restart --stop-signal TERM --map-signal HUP:TERM app"

[tasks.build]
description = "Build Kubernetto"
sources = [
	"cmd/**/*.go",
	"internal/**/*.go",
	"internal/**/*.templ",
	"internal/server/ui/assets/**",
	"go.mod",
	"go.sum",
	"!internal/server/**/*_templ.go",
]
outputs = [
	"kubernetto",
	"internal/server/ui/*_templ.go",
]
run = """
go generate ./...
go build -o ./kubernetto ./cmd/kubernetto
"""

[tasks.app]
hide = true
depends = "build"
sources = [
	"cmd/**/*.go",
	"internal/**/*.go",
	"internal/**/*.templ",
	"internal/server/ui/assets/**",
	"go.mod",
	"go.sum",
	"!internal/server/**/*_templ.go",
]
run = "exec ./kubernetto"
