[tools]
go = "1.26.4"
node = "latest"
pnpm = "latest"

[tasks.dev]
description = "Run Kubernetto"
raw_args = true
run = "exec go run ./cmd/kubernetto"

[tasks.build]
description = "Build Kubernetto"
run = """
pnpm build:assets
go generate ./...
go build -o ./kubernetto ./cmd/kubernetto
"""
